$(document).ready(function(){
  $("#empress").hover(function(){
    $("#empressp").slideDown()
  },function(){
    $("#empressp").slideUp()
  });
  $("#monica").hover(function(){
    $("#monicap").slideDown()
  },function(){
    $("#monicap").slideUp()
  });
});
