$(document).ready(function(){
  $("#empress").hover(function(){
    $("#empressp").slideDown()
  },function(){
    $("#empressp").slideUp()
  });
  $("#monica").hover(function(){
    $("#monicap").slideDown()
  },function(){
    $("#monicap").slideUp()
  });
  $("#njoro").hover(function(){
    $("#njorop").slideDown()
  },function(){
    $("#njorop").slideUp()
  });
  $("#selina").hover(function(){
    $("#selinap").slideDown()
  },function(){
    $("#selinap").slideUp()
  });
  $("#sj").hover(function(){
    $("#sjp").slideDown()
  },function(){
    $("#sjp").slideUp()
  });
});
